### ISSUE TITLE
Memory problem 

### ISSUE THREAD

**Issue by wfcola** [mmcza/TurtleBot-RRT-Star#1]
In line 318, value of nullptr will go through the while condition, which caused the exception of memory.   This situation follows  line 294.
```
294 global_path.poses.insert(global_path.poses.begin(), pose);
```
I try to fixed with:
```      
cur_ver = cur_ver->parent;
if (cur_ver->parent == nullptr) {
    RCLCPP_INFO(node_->get_logger(), "Reached the start of the path (parent is null). Exiting loop.");
    break;
}
if (reinterpret_cast<uintptr_t>(cur_ver->parent) < 0x1000 || reinterpret_cast<uintptr_t>(cur_ver->parent) > 0x7fffffffffff) {
    RCLCPP_ERROR(node_->get_logger(), "Detected invalid parent address: %p. Exiting loop.", cur_ver->parent);
    break;
}
```
Any ideas with the problem?

**Comment by mmcza** [comment]
Hi, I'll take a look at this and try to fix it. It shouldn't be an issue with `nullptr`, as it wouldn't satisfy the loop condition, but probably when rerouting some pointers are wrongly assigned.

**Comment by mmcza** [comment]
@wfcola I changed the tree to be a vector of unique pointers and tested it few times and never got any error (I also removed logging in console as I forgot about it earlier).

I will close the issue, but if you come across this or other issue feel free to reopen it.
